sudo: required
services:
  - docker

before_install:
  - docker build -t japca/docker-test -f Dockerfile.dev .

scripr:
  - 'sudo gem install bundler'
  - docker run japca/docker-test npm run test -- --coverage
